### ISSUE TITLE
Add header image

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/samanthasunne#1]
Add header image of Louisiana. https://upload.wikimedia.org/wikipedia/commons/1/1d/New_Orleans_Map_1863.jpg

This image should load quickly, and likely will not appear on mobile sites. (Not enough space!)

**Comment by samanthasunne** [comment]
If this is quite transparent, and doesn't interfere with the content on the page, let's try it

**Comment by ludstuen90** [comment]
Added with earlier MR
