### ISSUE TITLE
align employer logos on tutorials page

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#100]
last box in the tutorials banner is lower than the rest

![Screen Shot 2020-09-08 at 1 18 03 PM](https://user-images.githubusercontent.com/1383000/92513432-eaedc300-f1d5-11ea-81c1-a51748f65e3b.png)

**Comment by ludstuen90** [comment]
This got fixed in the code cleanup: 
![image](https://user-images.githubusercontent.com/6817579/93693035-e1ffca00-fad0-11ea-9f24-8f015bca479b.png)

**Comment by samanthasunne** [comment]
Yep, if it looks like that once implemented, then great

**Comment by ludstuen90** [comment]
Updates deployed! @samanthasunne
