### ISSUE TITLE
increase space above employer images on main page

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#101]
Can you insert a little more space between the bio text and the row of employer images on the main page? They're just a little too close together

**Comment by ludstuen90** [comment]
@samanthasunne  How does this look ? (If it looks good here, let me know and I can deploy to the site) 
![image](https://user-images.githubusercontent.com/6817579/103142969-fb299f80-46eb-11eb-81a8-4901e1e175dd.png)

**Comment by samanthasunne** [comment]
Yes that looks good! Please implement

**Comment by ludstuen90** [comment]
Deployed with https://github.com/ludstuen90/samanthasunne/pull/105
Ready for final approval and closure!  
@samanthasunne
