### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/samanthasunne#15]
Another quick feature we could do if you like is to customize the 404 error page. 

Here's what we have so far: 
![image](https://user-images.githubusercontent.com/6817579/49742494-7049e980-fc77-11e8-905e-77591a9825c3.png)

If you're interested in this, I could write something up!

**Comment by samanthasunne** [comment]
Can we add this clip art center-left? http://www.publicdomainfiles.com/show_file.php?id=13976238624403

**Comment by ludstuen90** [comment]
Done! How's this? Threw in a fleur de lis for free

![image](https://user-images.githubusercontent.com/6817579/49761819-cf732280-fca6-11e8-96f3-5b3b2310f1cb.png)

**Comment by samanthasunne** [comment]
I like it! Instead of "We've hit a dead end [fleur]" though, let's do "Uh oh! There doesn't seem to be anything here." w/ no fleur de lis

**Comment by ludstuen90** [comment]
Period added!
