### ISSUE TITLE
make margins narrower on mobile

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#38]
Not sure if this is even possible... but the mobile version would look better if the content could stretch wider on the screen. This applies to all three pages

![img_0089](https://user-images.githubusercontent.com/1383000/50916114-ed47ba80-13ff-11e9-9218-fe2a647f5189.PNG)

**Comment by ludstuen90** [comment]
Fixed! How's this look? Marigns are more equally distributed on mobile, desktop version unaffected. 

![image](https://user-images.githubusercontent.com/6817579/53305728-d3edb700-3863-11e9-9b0d-9757520f97b6.png)

**Comment by samanthasunne** [comment]
Great!!! 👏
