### ISSUE TITLE
resume icons squish vertically instead of retaining their shape

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#42]
When narrowing a window on desktop, the resume icons get compressed vertically. They should resize, but keep their original aspect ratio like the other images

![screen shot 2019-01-09 at 11 18 51 am](https://user-images.githubusercontent.com/1383000/50916335-7e1e9600-1400-11e9-9027-b3fb18782d00.png)

**Comment by ludstuen90** [comment]
Fixed with https://github.com/ludstuen90/samanthasunne/pull/44
