### ISSUE TITLE
re-center header image

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#48]
I would like the logo header image to be more centered between the nav menu and the body content, if possible. Right now it's a little higher than center.

![screen shot 2019-01-12 at 3 25 30 pm](https://user-images.githubusercontent.com/1383000/51078652-6ce2bd00-167e-11e9-875f-0eb6911acc45.png)

**Comment by samanthasunne** [comment]
Another idea: right now, the header image is like 1000px wide but most of it is whitespace. Could we have the logo itself be only about 500px wide, but centered in the header area? That way it would look better on mobile, too.

**Comment by ludstuen90** [comment]
Done and deployed! CTRL + SHIFT + R to clear the cache and see updates.
How's this look? If good, would you mind closing the issue to indicate all is well? 

Thanks!!!
