### ISSUE TITLE
get security cert for TFR

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#49]
while we're at it, can you try get a security certification for Tools for Reporters? It's hosted on Hostgator and run on Wordpress, so I think this is the thing to look at: https://www.hostgator.com/help/article/hostgator-free-ssl

**Comment by ludstuen90** [comment]
Absolutely, I can do this! When you get a minute, do you want to email me the info on how to get into the server?

**Comment by samanthasunne** [comment]
So, this site runs on Wordpress same as samanthasunne.com, but it's hosted by Hostgator instead of my dad's company. Does this help? I don't know how this stuff works.

![screen shot 2019-02-08 at 1 24 00 pm](https://user-images.githubusercontent.com/1383000/52500978-d8984700-2ba4-11e9-8b5b-1c4616533c25.png)

**Comment by samanthasunne** [comment]
Ok, it looks like I can pay Hostgator a onetime $10 fee to install a SSL certificate from somewhere else. It says:

"If you've purchased an SSL Certificate from another company (most likely packaged up as a .zip file) there will be 3 different sections of the certificate which you will need to paste into the appropriate fields below. SSL Certificate, RSA Private Key, SSL CA Certificate (Trusted Authority / "CA Bundle")"

If we get a free cert from that website you mentioned, do you think we can copy/paste in that stuff?

**Comment by ludstuen90** [comment]
Awesome, thanks for doing all the research on this! It looks like with HostGator it should be a piece of cake in the first link you sent. Woo! Do you want to email me instructions on how to get into the WordPress instance so I can install the plugin? It looks from these instructions here like I will need a WP Admin account, and FTP/SSH  access https://wordpress.org/plugins/wordpress-https/#faq

**Comment by samanthasunne** [comment]
I just created an admin account for you on Wordpress and emailed you the info. Also created an FTP account and sent you the info... let me know if that doesn't work

**Comment by ludstuen90** [comment]
TFR now has padlock icon! (Forcing SSL connections) 
We'll now need to update Google Analytics and Google Webmaster tools, if we use them.
 https://really-simple-ssl.com/knowledge-base/how-to-setup-google-analytics-and-google-search-consolewebmaster-tools/

If any other tools exist, would be a good idea to direct them to https://toolsforreporters.com!

**Comment by ludstuen90** [comment]
If all looks good, would you mind closing to indicate acceptance?

**Comment by samanthasunne** [comment]
Yes!!!!
