### ISSUE TITLE
homepage elements not aligned

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#50]
oh no! I opened the site randomly today and the elements are out of alignment again

![screen shot 2019-01-23 at 9 14 50 pm](https://user-images.githubusercontent.com/1383000/51654210-0d28c380-1f54-11e9-85cd-1364d6c22ea2.png)

**Comment by ludstuen90** [comment]
Fixed alignment on home page text, next up: fix alignment on proud projects right hand side

**Comment by samanthasunne** [comment]
looks good now! can you tell why it went out of alignment when it was aligned before?

**Comment by ludstuen90** [comment]
Awesome, good deal! Nothing would have changed, we likely both just missed
it somehow
