### ISSUE TITLE
replace header image

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#52]
Last issue, hopefully: I'd like to replace the header logo with the one attached here. (If it got resized too small as an attachment, let me know.)

This header should be centered on desktop so that it looks similar to the one we have now, but on mobile it should pretty much fill the width of the screen. Does that make sense?

![logo](https://user-images.githubusercontent.com/1383000/52022076-8e340d80-24b4-11e9-8043-ddf054c1b70e.png)

**Comment by ludstuen90** [comment]
Absolutely, I can do this! Commenting to confirm receipt of issue.

**Comment by ludstuen90** [comment]
Updated! Will require clearing cache to get the CSS updates. How does this look? Assigning to you for review!

**Comment by ludstuen90** [comment]
Add another logo breakpoint to smooth transition of window resizing 
https://github.com/ludstuen90/samanthasunne/pull/57
