### ISSUE TITLE
increase space between homepage elements

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#53]
I think the homepage is too crowded. I would like a bit more space between the nav menu, header image, bio photo/text, news org icons, and proud-projects. Let's say about 50% more space in each. If doable.

**Comment by ludstuen90** [comment]
Absolutely, I can do this! When you get a minute, do you want to email me the info on how to get into the server?

**Comment by ludstuen90** [comment]
Absolutely, I can do this! Commenting to confirm receipt of issue.

**Comment by ludstuen90** [comment]
@samanthasunne Spaces added! How does this look? We can make any adjustments really quickly.
