### ISSUE TITLE
justify tutorials image at the top

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#60]
The image of me on the /tutorials page is centered, relative to the table to the right, but I'd rather have it justified to the top, underneath the header "Tutorials."

![Screen Shot 2019-05-09 at 12 12 19 PM](https://user-images.githubusercontent.com/1383000/57469126-e5840f80-7253-11e9-92f9-ba4761832107.png)

**Comment by ludstuen90** [comment]
All done! How does this look? On my end, things look good both on desktop and mobile versions 💪🏻
![image](https://user-images.githubusercontent.com/6817579/57574830-94704900-7416-11e9-8faa-21372b58c466.png)
