### ISSUE TITLE
align text on homepage

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#61]
The intro text on the [homepage](https://www.samanthasunne.com) should line up vertically with the main image

**Comment by ludstuen90** [comment]
@samanthasunne Here we are, with fixed identified. Included screenshots of the site for desktop and a few common cell phones for reference

Fix identified. Site after change (Desktop), scrolled down slightly to see before and after intro text: 
![image](https://user-images.githubusercontent.com/6817579/82130678-f4c16580-97a3-11ea-9fcd-09cd9d5a379d.png)

Site **before** change (Desktop) -- similarly, scrolled down slightly to see before and after intro text: 
![image](https://user-images.githubusercontent.com/6817579/82130679-0145be00-97a4-11ea-9c66-ebcd6630e2e0.png)

Site **after** change, (iphone 6/7/8): 
![image](https://user-images.githubusercontent.com/6817579/82130640-96948280-97a3-11ea-88c0-ecff4bf3ecb0.png)

Site **after** change (iphone X): 
![image](https://user-images.githubusercontent.com/6817579/82130650-a744f880-97a3-11ea-85b7-aa313e3e35e2.png)

Site **after** change, (Galaxy S5): 
![image](https://user-images.githubusercontent.com/6817579/82130655-b166f700-97a3-11ea-9539-33779965b57f.png)

**Comment by ludstuen90** [comment]
This fix also looks good on iPad Pro. 

I noticed also on the current site (with or without this implementation of this fix), with iPad vertical mode, the intro paragraph gets a little squeezed: 
![image](https://user-images.githubusercontent.com/6817579/82130769-c2fcce80-97a4-11ea-90e6-a096df1a1e57.png)

On the current site (also with or without this fix), when switching to vertical mode, this is fixed. 
![image](https://user-images.githubusercontent.com/6817579/82130779-e889d800-97a4-11ea-9670-aeb69c327c53.png)

**Comment by samanthasunne** [comment]
Looks great, please implement, thanks!

**Comment by ludstuen90** [comment]
@samanthasunne  Done! You might have to do a hard-refresh (clear cache) to see the updates. If looks good, do you want to close this issue?
