### ISSUE TITLE
Investigate two hosting providers

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/samanthasunne#68]
Look at AWS and Azure to see what the two might cost, and if there is any clear advantage to one over the other.  

This investigation will include the following required components (Azure terms used): 
* App service
* SQL Database (Verify if MySQL is required, or another kind can be used)
* Public IP address

Additional components: 
* Application Gateway (Firewall)

**Comment by ludstuen90** [comment]
AWS equivalents: 
Azure App Service -- AWS Elastic Beanstalk

**Comment by ludstuen90** [comment]
It looks like we have a few options: 
Amazon LightSail: https://aws.amazon.com/lightsail/ 
Very easy option to get started, and says it offers plans starting at $3.50 per month; it would be everything we need to get a wordpress site up and running... IP, database, server, etc. A potential downside, is it looks like it doesn't do any automatic updates. That would mean it would be good to periodically revisit to install updates manually.


There's another option that requires more custom setup, but we could set up a patch schedule so urgent patches get applied automatically. We would set up a Linux server on an EC2 instance. We could install the site on that. It looks like they have a promo which is free for the first year, otherwise should be around $10 per month after that. 
https://aws.amazon.com/ec2/

**Comment by ludstuen90** [comment]
The option I found on Azure would be similar to the EC2 instance. In total, $10-15 per month.

**Comment by samanthasunne** [comment]
Sorry I missed all this! I guess LightSail is my favorite option because it's so cheap and has everything we need. Can it add a firewall? And is it easy for you to set up?

**Comment by ludstuen90** [comment]
Yes indeed, Lightsail has a default firewall that would be a good defense for the server: https://lightsail.aws.amazon.com/ls/docs/en_us/articles/understanding-firewall-and-port-mappings-in-amazon-lightsail

Moving forward with Lightsail, with a firewall configured
