### ISSUE TITLE
prevent black border around website on Opera

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#79]
When refreshing or opening a new page, a black border appears momentarily around the webpage. This happens on Opera and not Chrome (not sure about other browsers).

![frame border](https://user-images.githubusercontent.com/1383000/86636207-a35e7700-bf99-11ea-85b8-83aa5cbcf5eb.gif)

**Comment by ludstuen90** [comment]
All fixed! To see the updates, you'll have to clear the cache in the browser so it accepts the new CSS files.

**Comment by ludstuen90** [comment]
Related PR: https://github.com/ludstuen90/samanthasunne/pull/86
