### ISSUE TITLE
remove whitespace below header image

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#80]
I would like there to be less whitespace between the header logo and the body of the webpage, pictured below:

![Screen Shot 2020-07-06 at 2 28 37 PM](https://user-images.githubusercontent.com/1383000/86636327-c4bf6300-bf99-11ea-99d5-d68727815467.png)

**Comment by ludstuen90** [comment]
New site would look like this on desktop: 
![image](https://user-images.githubusercontent.com/6817579/87181246-58ee3a80-c2b8-11ea-92ba-7e87d6fb1a7f.png)

And this on iPad:
![image](https://user-images.githubusercontent.com/6817579/87181310-7c18ea00-c2b8-11ea-8140-f422c7819081.png)

And on mobile: 
![image](https://user-images.githubusercontent.com/6817579/87181301-74594580-c2b8-11ea-9f99-5a8b73c19dcd.png)

Only thing to note is that this view doesn't have the other header changes applied

**Comment by samanthasunne** [comment]
Yes, let's go ahead and implement that

**Comment by ludstuen90** [comment]
@samanthasunne I was reviewing, it looks like I closed this by accident, without final review
