### ISSUE TITLE
remove whitespace above nav menu

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#81]
I would like there to be less whitespace between the top of the page and the nav menu (and header image)

![Screen Shot 2020-07-06 at 2 28 37 PM](https://user-images.githubusercontent.com/1383000/86636513-fc2e0f80-bf99-11ea-8451-61171f02bfb0.png)

**Comment by ludstuen90** [comment]
How does this look?


<table>
<tr>
<td>Current Site</td>

<td>Updated Header</td>
</tr>

<tr>
<td>
<img src="https://user-images.githubusercontent.com/6817579/87177355-e5492f00-c2b1-11ea-8adf-fb9b3b3871ba.png">
</td>

<td>
<img src="https://user-images.githubusercontent.com/6817579/87177302-cfd40500-c2b1-11ea-9c7f-27bf920079d1.png">
</td>
</tr>

</table>

**Comment by ludstuen90** [comment]
Mobile site should look about the same: 
![image](https://user-images.githubusercontent.com/6817579/87177480-1590cd80-c2b2-11ea-853a-22b8179e276e.png)


Tablets, like the iPad Pro, would see reduced header space: 

<table>
<tr>
<td>Current Site</td>

<td>Updated Header</td>
</tr>

<tr>
<td>
<img src="https://user-images.githubusercontent.com/6817579/87177601-52f55b00-c2b2-11ea-9567-42dfe4520112.png">
</td>

<td>
<img src="https://user-images.githubusercontent.com/6817579/87177561-407b2180-c2b2-11ea-91e6-33e7708faf56.png">
</td>
</tr>

</table>


Tablet views, like iPad Pro would see updated header like this:

**Comment by samanthasunne** [comment]
Updated version looks better... can you implement that and I'll take another look at the live version?

**Comment by ludstuen90** [comment]
Changes deployed to production. Ready for feedback @samanthasunne
