### ISSUE TITLE
website not loading on Firefox

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#82]
Firefox error message: "The server at www.samanthasunne.com is taking too long to respond."

**Comment by ludstuen90** [comment]
Suspected error with Hover nameservers; updated to use Amazon's nameservers. Website now resolves on my cellphone.

**Comment by ludstuen90** [comment]
@samanthasunne  I know we just tried this a bit ago, but when you have a minute, would you mind trying running in the terminal again: 
sudo killall -HUP mDNSResponder

Clearing firefox cache, and then seeing if the site works?

**Comment by samanthasunne** [comment]
as of July 9, the only one it does not work on is Firefox. even after clearing the cache and running the killall command

**Comment by ludstuen90** [comment]
Contacted via WhatsApp to request more info on response from Firefox browser related to two screens - the DNS page, and the DNS search page: 
![image](https://user-images.githubusercontent.com/6817579/87181514-d7e37300-c2b8-11ea-8413-f795bd4bb1ae.png)

Also, requested to retry DNS clear cache command 48 hours after initial command to see if request has finished propagating.

**Comment by samanthasunne** [comment]
Screenshot of DNS lookup from my computer:
![Screen Shot 2020-07-10 at 1 21 40 PM](https://user-images.githubusercontent.com/1383000/87186059-6b647600-c2b0-11ea-9cb6-73fb94f12865.png)

**Comment by samanthasunne** [comment]
On 7/13/20: Site worked on Sammi's desktop Opera - but not in an incognito window! It did work on Tor desktop and on Opera mobile.

Firefox is still not working, even after connecting to a mobile hotspot, running the CLI command and clearing history and cache. Screenshots below.

![Screen Shot 2020-07-13 at 10 10 28 AM](https://user-images.githubusercontent.com/1383000/87320896-27ac7f00-c4f1-11ea-9b38-9008b2e56af5.png)

![Screen Shot 2020-07-13 at 10 09 55 AM](https://user-images.githubusercontent.com/1383000/87320889-23806180-c4f1-11ea-9f88-58b41f35e3b9.png)

**Comment by ludstuen90** [comment]
Completed support call with Hover, fixed issue by adding a www subdomain entry
