### ISSUE TITLE
remove whitespace above footer

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#85]
I would like less whitespace between the footer and the body content, pictured here:

![Screen Shot 2020-07-06 at 2 28 49 PM](https://user-images.githubusercontent.com/1383000/86637246-db19ee80-bf9a-11ea-8718-7a71efd34a95.png)

**Comment by ludstuen90** [comment]
How does this look?

<table>
<tr>
<td>Page</td>
</td>
<td>Current Site</td>
</td>
<td>With Change</td>
</td>
</tr>

<tr>
<td>Homepage</td>
</td>
<td><img src="https://user-images.githubusercontent.com/6817579/87105887-85f80a00-c232-11ea-836c-432b8a48567d.png">

</td>
</td>
<td> <img src="https://user-images.githubusercontent.com/6817579/87105870-7a0c4800-c232-11ea-93f6-3bf408320253.png">
</td>
</td>
</tr>



<tr>
<td>Tutorials</td>
</td>

<td><img src="https://user-images.githubusercontent.com/6817579/87106018-ce172c80-c232-11ea-9a93-d44236ccfd52.png">
</td>
</td>
<td> <img src="https://user-images.githubusercontent.com/6817579/87106033-da02ee80-c232-11ea-8ae2-0a55c8b3e544.png">
</td>
</td>
</tr>


<tr>
<td>Projects</td>
</td>

<td><img src="https://user-images.githubusercontent.com/6817579/87106084-fc950780-c232-11ea-97e4-6f0e3cffcc52.png">
</td>
</td>
<td> <img src="https://user-images.githubusercontent.com/6817579/87106110-0e76aa80-c233-11ea-8ab0-9c8a0439ee62.png">
</td>
</td>
</tr>


</table>

**Comment by ludstuen90** [comment]
Linked PR: https://github.com/ludstuen90/samanthasunne/pull/87

**Comment by samanthasunne** [comment]
I would prefer if there was even less whitespace than that, but if that's a lot of work, your version is ok

**Comment by ludstuen90** [comment]
No problem at all, what I had pictured is 3.0em. 
Here's what it looks like with 1.5em


![image](https://user-images.githubusercontent.com/6817579/87175942-bcc03580-c2af-11ea-81fe-760852332974.png)


![image](https://user-images.githubusercontent.com/6817579/87175966-c5b10700-c2af-11ea-83bc-dcd9cb73ea29.png)


![image](https://user-images.githubusercontent.com/6817579/87175982-cd70ab80-c2af-11ea-8029-7a7e126463a4.png)

How does this look ? @samanthasunne

**Comment by samanthasunne** [comment]
1.5em looks good!

**Comment by ludstuen90** [comment]
Changes released to production. If looks good, please feel free to close issue @samanthasunne
