### ISSUE TITLE
center the body content on mobile

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#88]
the body content of all three pages shows up as justified left on my iphone:

![IMG_0562](https://user-images.githubusercontent.com/1383000/87108949-09146280-c229-11ea-8eb6-0559f5b8e156.PNG)

**Comment by ludstuen90** [comment]
Here are a few screenshots as viewed from an Iphone 6/7/8: 

![image](https://user-images.githubusercontent.com/6817579/87184879-2b58bf80-c2bf-11ea-9092-4dd9b181b9cd.png)
![image](https://user-images.githubusercontent.com/6817579/87184924-3d3a6280-c2bf-11ea-8294-e9a3d8817926.png)


tutorials
![image](https://user-images.githubusercontent.com/6817579/87185951-049b8880-c2c1-11ea-8ae0-d33c63d94868.png)

![image](https://user-images.githubusercontent.com/6817579/87185979-0e24f080-c2c1-11ea-8402-32790723c5b1.png)


![image](https://user-images.githubusercontent.com/6817579/87185998-167d2b80-c2c1-11ea-98f1-2eb0a9062028.png)


![image](https://user-images.githubusercontent.com/6817579/87186041-298ffb80-c2c1-11ea-9542-4f5e56bb2e10.png)

**Comment by samanthasunne** [comment]
Is it possible to implement that, but make the margins narrower? It looks too squished in the middle

**Comment by ludstuen90** [comment]
@samanthasunne  absolutely, here's just a bit more space, specifically on the right hand side 
![image](https://user-images.githubusercontent.com/6817579/87199840-af1ba780-c2d1-11ea-97cf-dead4580aa5f.png)

**Comment by samanthasunne** [comment]
Yes, that looks better thanks. Let's go ahead and implement that

**Comment by ludstuen90** [comment]
Changes deployed to site, ready for approval @samanthasunne

**Comment by ludstuen90** [comment]
Actually, hang on - making one quick adjustment to the first line

**Comment by ludstuen90** [comment]
Changes temporarily reverted from production site.

**Comment by ludstuen90** [comment]
Hotfix deployed, and deployed to site. @samanthasunne  ready for review!

**Comment by samanthasunne** [comment]
Can you make the content even wider? Some stuff is still cut off. Maybe it can be just like 10% margins on either side? As wide as possible without taking up the whole screen

![IMG_264C2FFFB863-1](https://user-images.githubusercontent.com/1383000/87881769-0bad4f80-c9c1-11ea-9c61-e96607d856b1.jpeg)

**Comment by ludstuen90** [comment]
Good catch on that one! I checked, and it looked good on the feature branch, something must have happened when we merged all the changes in together. 

Here's increasing the margins to nearly fill up the page: 
![image](https://user-images.githubusercontent.com/6817579/88497369-8e707480-cf96-11ea-89f4-a198851f2d48.png)
![image](https://user-images.githubusercontent.com/6817579/88497382-96301900-cf96-11ea-81a9-5b21fc9028e8.png)
![image](https://user-images.githubusercontent.com/6817579/88497391-9cbe9080-cf96-11ea-9535-60779e8f4a25.png)

![image](https://user-images.githubusercontent.com/6817579/88497402-a5af6200-cf96-11ea-864f-b3fe333bd30f.png)
![image](https://user-images.githubusercontent.com/6817579/88497416-acd67000-cf96-11ea-84a6-8f61ceded3a1.png)
![image](https://user-images.githubusercontent.com/6817579/88497426-b364e780-cf96-11ea-9497-abf1595c5f64.png)
![image](https://user-images.githubusercontent.com/6817579/88497444-bd86e600-cf96-11ea-94aa-35b5aad85c07.png)

screen caps as viewed on an iphone 6 @samanthasunne

**Comment by samanthasunne** [comment]
That looks good, please go ahead and implement!

**Comment by ludstuen90** [comment]
@samanthasunne  Awesome, deployed! Feel free to close if looks good

**Comment by samanthasunne** [comment]
Yes, except the lines "Click here for more projects" and "Click here for a full resume" are still justified left

![IMG_0576](https://user-images.githubusercontent.com/1383000/88797766-78ff7400-d169-11ea-9254-4354e3b32833.PNG)

Also the logo and the first image seem off? I think maybe the logo is slightly indented right but I can't tell

![IMG_0577](https://user-images.githubusercontent.com/1383000/88797769-79980a80-d169-11ea-8fa9-111649eafea9.PNG)

**Comment by ludstuen90** [comment]
@samanthasunne  You're right, the logo is off! I did a pretty thorough house-cleaning of the code, and simplified it a lot. I think this gets us much closer to the design we were looking for, with the margins at the side of the page as small as possible on mobile: 
![image](https://user-images.githubusercontent.com/6817579/93692917-7d903b00-facf-11ea-8cb6-5f2b51554ee2.png)
![image](https://user-images.githubusercontent.com/6817579/93692935-b4665100-facf-11ea-8090-504d8d2a22d4.png)
![image](https://user-images.githubusercontent.com/6817579/93692942-d233b600-facf-11ea-99c7-4bd5996ae97e.png)
![image](https://user-images.githubusercontent.com/6817579/93692965-0d35e980-fad0-11ea-8206-f3344912aa0a.png)


Adding a row property to the projects and resume lines, which were appearing left-justified: 
![image](https://user-images.githubusercontent.com/6817579/93692989-4c643a80-fad0-11ea-83bf-ee6d71cd3fcb.png)

![image](https://user-images.githubusercontent.com/6817579/93692976-2c347b80-fad0-11ea-901e-b37d5bc1cbb7.png)


Also, as I was simplifying things, I found a bug where the Merriweather font we had picked out was getting overridden by another file!  This gets the site back to: 
![image](https://user-images.githubusercontent.com/6817579/93692821-4705f080-face-11ea-900e-02587797b37f.png)

**Comment by ludstuen90** [comment]
Homepage as viewed from desktop: 
![image](https://user-images.githubusercontent.com/6817579/93693122-07410800-fad2-11ea-9511-0ab6a48a2627.png)

![image](https://user-images.githubusercontent.com/6817579/93693148-4d966700-fad2-11ea-84eb-0b6487098922.png)

**Comment by ludstuen90** [comment]
![image](https://user-images.githubusercontent.com/6817579/93693165-6b63cc00-fad2-11ea-9936-0210d45d4566.png)
![image](https://user-images.githubusercontent.com/6817579/93693168-76b6f780-fad2-11ea-8ac2-63ad28437f0c.png)
![image](https://user-images.githubusercontent.com/6817579/93693172-7d456f00-fad2-11ea-96d8-c6771bf9ab87.png)
![image](https://user-images.githubusercontent.com/6817579/93693174-846c7d00-fad2-11ea-9240-e36071a50af2.png)

**Comment by ludstuen90** [comment]
For the last file, I can try a new way to send over the files - can you open this link to view the saved versions of the pages ?
https://drive.google.com/drive/folders/1y6pesfNotpLwnecm3pzQ_Z_6Po9_nndo?usp=sharing

**Comment by samanthasunne** [comment]
Ok this looks good. On my phone, the "click here" lines are still justified left, but I can't tell if you've implemented your changes yet or not

**Comment by ludstuen90** [comment]
@samanthasunne  Updates deployed! Would you mind taking a look and letting me know how things look? I did a pretty thorough code clean up

**Comment by samanthasunne** [comment]
Ok. So. This is terrible... but I think I want all the text justified left on mobile 😶  I looked through some similar sites and they have all their text justified left on mobile, and it looks better.

So: on mobile I would like images centered but text justified left. 

And the 10% margins look fine, although we might want to make the margins bigger once we implement these changes too. Sorryyyy

**Comment by ludstuen90** [comment]
@samanthasunne  Updates deployed to make things left-justified. How do the margins look ? Any changes, let me know!

**Comment by samanthasunne** [comment]
One tiny thing and then I'll close this issue... the text is right up against the top image on the About page

![IMG_1066](https://user-images.githubusercontent.com/1383000/106075796-f5045580-60d3-11eb-9a73-bc4c73fe9067.PNG)

**Comment by ludstuen90** [comment]
@samanthasunne  All fixed and deployed! How does this look ? 
![image](https://user-images.githubusercontent.com/6817579/106369004-ccc36380-632c-11eb-87a7-8047ae188a9c.png)
