### ISSUE TITLE
make static images on mobile larger

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#93]
The news org logos on mobile are pretty small. Can you make them roughly equal the size of the "proud projects" images below?

![IMG_264C2FFFB863-1](https://user-images.githubusercontent.com/1383000/87881813-5e870700-c9c1-11ea-8ed0-776764914b06.jpeg)

**Comment by ludstuen90** [comment]
Just to make sure we don't run into another scenario where one change affects another, if it's ok with you we can wait until merging in #88 to make this change @samanthasunne

**Comment by ludstuen90** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/6817579/88746365-c3113700-d122-11ea-8bfe-58c3deb96b5e.png)


This will also affect the universities banner: 
![image](https://user-images.githubusercontent.com/6817579/88746520-226f4700-d123-11ea-83ff-ca88e9a08c53.png)




This branch also fixes a bug on iphone 5/5s where the last paragraph in the intro section appeared 20% to the right on error. 

![image](https://user-images.githubusercontent.com/6817579/88746482-0cfa1d00-d123-11ea-8ec5-d59e48b0c66f.png)

**Comment by samanthasunne** [comment]
Looks great!

**Comment by ludstuen90** [comment]
@samanthasunne  Awesome, deployed to site, ready for final review !
