### ISSUE TITLE
missing border on tutorials table

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#94]
Some of the top border of the Upcoming Appearances table has gone invisible

![Screen Shot 2020-07-21 at 4 25 03 PM](https://user-images.githubusercontent.com/1383000/88108689-e1999000-cb6e-11ea-97b6-4c1c78a36760.png)

**Comment by ludstuen90** [comment]
Here's with a fix that applies only to this table: 
![image](https://user-images.githubusercontent.com/6817579/88494170-21a3ad00-cf8b-11ea-9e8e-05903abe887f.png)

**Comment by samanthasunne** [comment]
Yep that looks good!

**Comment by ludstuen90** [comment]
Deployed! Feel free to close if looks good @samanthasunne
